"""Added organization table

Revision ID: 196dfdc81687
Revises: 2b61d5e61b99
Create Date: 2023-03-02 17:26:58.779886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '196dfdc81687'
down_revision = '2b61d5e61b99'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization')
    # ### end Alembic commands ###
